services:
  app:
    container_name: ms-observability-study
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: "/bin/bash -c 'composer install && php bin/hyperf.php server:watch'"
    volumes:
      - .:/var/www/app
      - ./docker/php/config/custom_xdebug.ini:/etc/php83/conf.d/99_xdebug.ini
    ports:
      - "80:9501"
    restart: unless-stopped
    networks:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    environment:
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - XDEBUG_MODE=${XDEBUG_MODE:-off}

  mysql:
    container_name: mysql-8
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_USER: ${DB_USERNAME:-"app"}
      MYSQL_PASSWORD: ${DB_PASSWORD:-"app"}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-"root"}
      MYSQL_DATABASE: ${DB_DATABASE:-"ms-observability-study"}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mysql

  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    restart: unless-stopped
    networks:
      - redis

  grafana:
    container_name: grafana
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - mysql
      - redis

networks:
  mysql:
    driver: bridge
  redis:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  grafana:
    driver: local
